version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - php-network

networks:
  php-network:
    driver: bridge